[features]
seeds = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

## /target is excluded from being pushed so upon cloning and 
## running anchor build and then anchor deploy
## newly created program addresses have to be pasted below
## as well as into respective programs and then need to run 
## anchor build and then anchor deploy
## AGAIN

[programs.localnet]
voting = "8q9Xm51HBw8s8DknD5P11RvBm2WovX2VageztBf2xdzH"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
testvoting = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test_voting.ts"

